require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/GuardClause:
  Enabled: true
  Exclude:
    - 'lib/fintech/shared/application/use_case.rb'
    - 'lib/fintech/shared/domain/*value_object.rb'

# Metrics

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - 'lib/fintech/**/domain/*_entity.rb'

# Tests

RSpec/MultipleExpectations:
  Exclude:
    - spec/requests/root_spec.rb

RSpec/ContextWording:
  Exclude:
    - spec/support/requests.rb

RSpec/Rails/InferredSpecType:
  Enabled: false
