require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/GuardClause:
  Enabled: true
  Exclude:
    - lib/fintech/shared/application/use_case.rb
    - lib/fintech/shared/domain/*value_object.rb

Style/ArgumentsForwarding:
  Enabled: true
  UseAnonymousForwarding: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
  Exclude:
    - config/providers/persistence.rb

# Metrics

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - lib/fintech/**/domain/*_entity.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - lib/tasks/fintech/task_helpers.rb
    - lib/fintech/orders/infrastructure/import_orders_job.rb

Metrics/BlockLength:
  Enabled: true
  CountAsOne: ["array", "hash", "method_call", "heredoc"]

Metrics/AbcSize:
  Enabled: true
  CountRepeatedAttributes: false
  Exclude:
    - lib/fintech/orders/infrastructure/import_orders_job.rb

# Tests

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - spec/requests/root_spec.rb
    - spec/lib/tasks/fintech/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Exclude:
    - spec/support/shared_contexts/rake.rb

RSpec/ExampleLength:
  Enabled: true
  CountAsOne: ["array", "hash", "method_call", "heredoc"]
  Max: 10

RSpec/ContextWording:
  Enabled: true
  Exclude:
    - spec/support/requests.rb
    - spec/support/shared_contexts/rake.rb

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/ReturnFromStub:
  Enabled: true
  EnforcedStyle: block

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - spec/lib/tasks/**/*

RSpec/MatchArray:
  Enabled: true
  Exclude:
    - spec/lib/tasks/fintech/orders/import_spec.rb
