require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/GuardClause:
  Enabled: true
  Exclude:
    - 'lib/fintech/shared/application/use_case.rb'
    - 'lib/fintech/shared/domain/*value_object.rb'

# Metrics

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - 'lib/fintech/**/domain/*_entity.rb'

# Tests

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - spec/requests/root_spec.rb
    - spec/lib/tasks/fintech/merchants/import_spec.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Exclude:
    - spec/support/shared_contexts/rake.rb

RSpec/ExampleLength:
  Enabled: true
  CountAsOne: ["array", "method_call", "heredoc"]
  Max: 10

RSpec/ContextWording:
  Enabled: true
  Exclude:
    - spec/support/requests.rb
    - spec/support/shared_contexts/rake.rb

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive
