version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.${ENV:-development}

  app:
    image: challenge-be-fintech-disbursements
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    depends_on:
      - db
    volumes:
      - .:/usr/app

volumes:
  postgres-data:
