version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.${ENV:-development}

  app:
    image: challenge-be-fintech-disbursements
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - .:/usr/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.2.3-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  sidekiq:
    image: challenge-be-fintech-disbursements
    restart: unless-stopped
    command: bundle exec sidekiq -r ./config/sidekiq.rb
    volumes:
      - redis-data:/data
    depends_on:
      - redis

volumes:
  postgres-data:
  redis-data:
